set up testing for pinia store
ourjapanlife/findadoc-web pull request #100
Opened 2022-10-31 01:45 UTC by RageZBla

Resolves #88

# What changed

- added following dependencies:
    - `@testing-library/vue`
    - `@vitejs/plugin-vue`
    - `jsdom`
    - `vitest`
- removed jest
- added new store for language navigation: `stores/navigationStore.js`
- added corresponding test `test/stores/navigationStore.spec.ts` 

# Testing instructions

run `yarn run test`, it should be 🟢

2022-10-31 05:49 UTC, theyokohamalife commented
@RageZBla There's one failing step in the CI. It looks like a dependency is missing.

2022-10-31 06:19 UTC, ermish requested changes
Nice! Just two changes

2022-10-31 06:19 UTC, ermish commented on stores/navigationStore.js
> +import { defineStore } from 'pinia'
This should be a .ts file, not js since this is a typescript based project.

2022-10-31 06:19 UTC, ermish commented on test/stores/navigationStore.spec.ts
> +describe('Counter Store', () => {
Should this be navigation store?

2022-11-03 12:18 UTC, ermish approved these changes
LGTM! :shipit:

2022-11-03 12:19 UTC, merged

2022-11-03 12:22 UTC, ermish commented
@RageZBla it looks like the workflow is still failing. I think it just needs a `yarn install`?