docs: update the Slack channel info and technologies
ourjapanlife/findadoc-web pull request #43
Opened 2022-07-26 15:39 UTC by theyokohamalife

# Resolves Issue #40 

1. Removes links to resources we no longer use
2. Updates the Slack channel information
3. Updates the technologies we use

2022-07-27 01:20 UTC, ann-kilzer commented on CONTRIBUTING.md
> +1. Join the `#localization` channel on Slack.
We don't have translation work at this time, but will soon

2022-07-27 01:21 UTC, ann-kilzer approved these changes
LGTM

Let's check that Netlify build... it's definitely unrelated but still strange

2022-07-27 06:51 UTC, theyokohamalife commented
> LGTM
> 
> Let's check that Netlify build... it's definitely unrelated but still strange

@ann-kilzer It looks like yarn is failing to download during the deployment process.

![Screen Shot 2022-07-27 at 3 50 16 PM](https://user-images.githubusercontent.com/31802656/181180696-0a62c7e6-c275-4970-9a9d-832710a2dcec.png)

2022-07-27 06:51 UTC, theyokohamalife commented
@ermish Is there anything you'd like added or changed?

2022-07-27 10:00 UTC, ermish requested changes
reviewed!

2022-07-27 10:00 UTC, ermish commented on CONTRIBUTING.md
>  ### Related Technologies
this section probably fits the readme better, so we could take it out here.

2022-07-27 10:00 UTC, ermish commented on CONTRIBUTING.md
>  ## Helpful Info
should remove since empty for now, unless we're planning to add content here soon

2022-07-27 10:00 UTC, ermish commented on CONTRIBUTING.md
>  👉️ Developers 💻️
might make these sections H3/H4 headers

2022-07-27 11:08 UTC, ermish commented
rebasing fixed the build ✨ 😺

2022-07-27 11:22 UTC, theyokohamalife commented
> rebasing fixed the build ✨ 😺

@ermish  Hmm... rebasing it shouldn't show all of the file changes though. Only the README and CONTRIBUTING should be changed. 🤔

2022-07-27 13:08 UTC, ann-kilzer commented
lol 
> +11,782 −25,323

make sure you have the latest main before rebasing???

2022-07-27 13:09 UTC, ann-kilzer requested changes
please fix the branch and then ping me and I'll approve asap 😊

2022-07-28 00:39 UTC, ann-kilzer approved these changes

2022-07-28 01:33 UTC, theyokohamalife commented
@ermish I fixed the rebase. Please review when you have a chance

2022-07-28 03:14 UTC, ermish approved these changes

2022-07-28 03:14 UTC, ermish commented
LGTM :shipit:

2022-07-28 06:20 UTC, merged