Feat: Implement ModDashboardLeftNavbar with partial functionality.
ourjapanlife/findadoc-web pull request #473
Opened 2024-05-17 05:01 UTC by NabbeunNabi

Resolves #451 

## 🔧 What changed
Before there was no LeftNavBar for the dashboard view of the moderation panel. Now it exists with partial functionality. It still needs the functionality with the fetching from the backend. This is mainly a UI component that has functions set up to change the state.

## 📸 Screenshots

-   ### Before

![image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/1f42b8e9-4288-46e8-90de-a0416f7abfc4)

-   ### After

![image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/d3b53958-21fe-4eaf-8270-b082a80659e1)

2024-05-17 13:22 UTC, theyokohamalife commented on components/ModDashboardLeftNavbar.vue
> +    displayText: "Facilities",
Let's wrap all the `displayText` in translatable strings using `$t('')`

2024-05-17 13:23 UTC, theyokohamalife requested changes
Looking great so far! Just needs a few small changes.

2024-05-19 20:21 UTC, NabbeunNabi commented
Added the translation string as requested. in the console is saying it defaults to the US since there is no Japanese for it at the moment. So I believe it is working as expected

2024-05-20 14:53 UTC, theyokohamalife approved these changes
LGTM ✨

2024-05-20 14:53 UTC, merged