feat: add cond for local server endpoint
ourjapanlife/findadoc-web pull request #500
Opened 2024-05-27 12:43 UTC by theyokohamalife

Resolves #[Issue number]

## 🔧 What changed

## 🧪 Testing instructions

## 📸 Screenshots

-   ### Before

-   ### After

2024-05-27 14:50 UTC, NabbeunNabi requested changes
I am following the backend readme and there are some issues there, which might lead to others not being able to use this command.

### Screenshots with Comments

- This command said it was not found
![image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/b99eeb1e-da44-40cb-bbaf-5a7923453d43)

- For PC this might be the chocolately command now to install java? [Chocolatey Java](https://community.chocolatey.org/packages/javaruntime )
-Current instructions for Java
![image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/ecf074a6-82d9-4b96-8971-c6634bbffef9)

-Got stuck started the firebase because I am not sure what to do here since the up and down arrows  did nothing

![image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/4c75b1bc-5538-4ac8-8727-13aee96bff8d)

So might need to fix the backend read me before merging this to make sure everyone can set it up to work on it properly before running this command

2024-05-27 20:19 UTC, NabbeunNabi approved these changes

2024-05-27 20:21 UTC, NabbeunNabi commented
I updated the readME by going through step by step. So this can be merged as long as this PR https://github.com/ourjapanlife/findadoc-server/pull/454 is merged

2024-06-02 14:26 UTC, ermish commented on package.json
> +        "dev:localdb": "NODE_ENV=development yarn && nuxi dev",
localdb doesn't make sense here as we're not starting a database. 
I would just add the NODE_ENV variable to the `dev` task

2024-06-02 14:28 UTC, ermish requested changes
reviewed!

2024-06-02 14:28 UTC, ermish commented on utils/graphql.ts
> +    let endpoint;
```suggestion
    let apiURL;
```

2024-06-02 14:28 UTC, ermish commented on utils/graphql.ts
> +        endpoint = "http://127.0.0.1:4000"
```suggestion
        apiURL = "http://127.0.0.1:4000"
```

2024-06-02 14:28 UTC, ermish commented on utils/graphql.ts
> +        endpoint = "https://api.findadoc.jp"
```suggestion
        apiURL = "https://api.findadoc.jp"
```

2024-06-02 14:28 UTC, ermish commented on README.md
> +$ yarn dev:localdb
would remove this. see next comment

2024-06-03 11:37 UTC, ermish approved these changes
everything looks good except the addition of a bunch of semicolons 🤔 do you have pretter installed or something?

2024-06-03 12:10 UTC, NabbeunNabi commented on utils/graphql.ts
> +        return gqlClient;
I use the ESLINT that you told me to use. `.prettierignore` is still there. I just changed the variable names. The semicolons were already there so I thought there might be a reason so I didn't remove them here.

2024-06-03 12:25 UTC, NabbeunNabi commented on utils/graphql.ts
> +        return gqlClient;
All gone. Can you check again @ermish

2024-06-03 14:39 UTC, merged

2024-06-04 10:12 UTC, ermish approved these changes
Sheep it 🐑