fixed failing cypress tests
ourjapanlife/findadoc-web pull request #550
Opened 2024-06-08 05:28 UTC by Tch4lla

Resolves #[Issue number]

## 🔧 What changed
In regards to moderation, Cypress doesn't have a '.tab()' command. I had to replace all tab commands to manually focus on the next input field in order for the error messages to be displayed.  I also needed to rewrite the structure of the clipboard function as cypress has a special way of dealing with the clipboard. 

In regards to the home test, due to the way that vue refreshes, I needed to add a small wait in order for the elements to appear in the dom 

## 🧪 Testing instructions

run cypress tests 

## 📸 Screenshots
![pas test](https://github.com/ourjapanlife/findadoc-web/assets/99618731/747b5261-2965-4e80-bd3b-5d4682bf6fac)

2024-06-08 07:05 UTC, theyokohamalife requested changes
I'm not sure from the PR description why we need this change. A package was installed that allows us to use tab() in tests. Is it not working as intended? Could you provide screenshots in the description?

2024-06-08 09:52 UTC, Tch4lla commented
> I'm not sure from the PR description why we need this change. A package was installed that allows us to use tab() in tests. Is it not working as intended? Could you provide screenshots in the description?

I reinstalled the plugin and tested it again. When running the tests, it never actually tabs and focuses on the next input value, which is what would trigger the error message to be displayed 

![image](https://github.com/ourjapanlife/findadoc-web/assets/99618731/b7b1f2b1-56e6-4d0e-997b-cf0dc21035dc)

2024-06-10 20:51 UTC, Tch4lla reviewed
If there is any more information needed please let me know

2024-06-11 03:46 UTC, theyokohamalife requested changes
I ran the tests again and confirmed that the `.tab()` is working on my local machine. It's also passing on CI. I think we should figure out why it's not working on your computer instead of removing it.

https://github.com/ourjapanlife/findadoc-web/assets/31802656/44e4857f-4942-4042-a6d9-776363fe359b

2024-06-11 04:02 UTC, theyokohamalife commented on cypress/e2e/moderationDashboard.cy.ts
> +                    // clipboardResult.should("exist", 10000);
Let's remove this instead of commenting it out.

2024-06-11 04:03 UTC, theyokohamalife commented on cypress/e2e/moderationDashboard.cy.ts
> -import "cypress-plugin-tab"
This package is needed in order for the `.tab()` to work.

2024-06-11 04:04 UTC, theyokohamalife commented on cypress/e2e/moderationDashboard.cy.ts
> +            //there is no cy.tab(), so manually need to shift focus from one input to another
Let's remove this comment. Also please see the screen recording I shared of `.tab()` working with the plugin installed.

Seeing as this is passing on CI and only failing on your local machine, I think we should try to figure out why before making changes to these tests.

2024-06-14 06:50 UTC, Tch4lla reviewed
Latest PR has updates to address these issues

2024-06-14 12:53 UTC, ermish commented
@theyokohamalife can you review this one again? there's overlap with your test fixes PR, so you'll have the most context

2024-06-23 08:39 UTC, closed without merging