feat: add mutation to delete existing facility
ourjapanlife/findadoc-web pull request #847
Opened 2024-10-23 00:46 UTC by NabbeunNabi

Resolves #844  
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specs

## 🔧 What changed
A mutation was added to delete a facility from our database. This is important because in Japan there are a lot of private clinics. They may close if a doctor retires or if the doctor decides to join another practice

## 🧪 Testing instructions
Tests will be added after the implementation of ticket #832

2024-10-23 01:02 UTC, Anissa3005 commented
@NabbeunNabi Maybe something we should think about is, do we want everyone that has access to the moderation panel to be able to delete a facility? Or only someone with certain authorization? Before we implement this I think we should be certain who is able to delete a facility.

2024-10-23 01:29 UTC, NabbeunNabi commented
> @NabbeunNabi Maybe something we should think about is, do we want everyone that has access to the moderation panel to be able to delete a facility? Or only someone with certain authorization? Before we implement this I think we should be certain who is able to delete a facility.

@Anissa3005 I agree that the implementation of how this mutation is used should be discussed. This is just adding the function to the store so that when we have that answer it can be used in the correct manner. I do think that OAuth provides different levels of Auth. So if a type of authentication is sent with the mutation it should check the authorization on the backend? Or if they are admin level authentication that this is available on the frontend. I wasn't planning on using the function right away. I just want them there so when the testing ticket gets resolved we can start testing the functionality and also use it when we have the answer to your question.

2024-10-25 03:17 UTC, NabbeunNabi commented
@ermish I also added the return type here. I looked at the backend to see what each one was returning to the frontend as a type

2024-10-29 02:35 UTC, ermish requested changes
🤖 Delete mode activated 🤖

2024-10-29 02:35 UTC, ermish commented on stores/facilitiesStore.ts
> +            } catch (error) {
we should return a failure state to the calling function so they can display a nice error to the user if this fails

2024-10-30 01:05 UTC, NabbeunNabi commented on stores/facilitiesStore.ts
> +                    gqlClient.request.bind(gqlClient),
@ermish We discussed how `graphQL` has a built in error response. So once we finish writing up the frontend pattern that is reusable, then we can add issues to apply the pattern to all of our calls

2024-11-05 11:56 UTC, merged